# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
